// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: ClientData.proto

package client_data_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConsumerClient is the client API for Consumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsumerClient interface {
	SubscribeOnScreenText(ctx context.Context, in *ClientDataRequest, opts ...grpc.CallOption) (Consumer_SubscribeOnScreenTextClient, error)
	Exec(ctx context.Context, opts ...grpc.CallOption) (Consumer_ExecClient, error)
}

type consumerClient struct {
	cc grpc.ClientConnInterface
}

func NewConsumerClient(cc grpc.ClientConnInterface) ConsumerClient {
	return &consumerClient{cc}
}

func (c *consumerClient) SubscribeOnScreenText(ctx context.Context, in *ClientDataRequest, opts ...grpc.CallOption) (Consumer_SubscribeOnScreenTextClient, error) {
	stream, err := c.cc.NewStream(ctx, &Consumer_ServiceDesc.Streams[0], "/client_data_pb.Consumer/SubscribeOnScreenText", opts...)
	if err != nil {
		return nil, err
	}
	x := &consumerSubscribeOnScreenTextClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Consumer_SubscribeOnScreenTextClient interface {
	Recv() (*ClientDataOnScreenTextResponse, error)
	grpc.ClientStream
}

type consumerSubscribeOnScreenTextClient struct {
	grpc.ClientStream
}

func (x *consumerSubscribeOnScreenTextClient) Recv() (*ClientDataOnScreenTextResponse, error) {
	m := new(ClientDataOnScreenTextResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *consumerClient) Exec(ctx context.Context, opts ...grpc.CallOption) (Consumer_ExecClient, error) {
	stream, err := c.cc.NewStream(ctx, &Consumer_ServiceDesc.Streams[1], "/client_data_pb.Consumer/Exec", opts...)
	if err != nil {
		return nil, err
	}
	x := &consumerExecClient{stream}
	return x, nil
}

type Consumer_ExecClient interface {
	Send(*ClientExecOutput) error
	CloseAndRecv() (*ClientExecData, error)
	grpc.ClientStream
}

type consumerExecClient struct {
	grpc.ClientStream
}

func (x *consumerExecClient) Send(m *ClientExecOutput) error {
	return x.ClientStream.SendMsg(m)
}

func (x *consumerExecClient) CloseAndRecv() (*ClientExecData, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ClientExecData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConsumerServer is the server API for Consumer service.
// All implementations must embed UnimplementedConsumerServer
// for forward compatibility
type ConsumerServer interface {
	SubscribeOnScreenText(*ClientDataRequest, Consumer_SubscribeOnScreenTextServer) error
	Exec(Consumer_ExecServer) error
	mustEmbedUnimplementedConsumerServer()
}

// UnimplementedConsumerServer must be embedded to have forward compatible implementations.
type UnimplementedConsumerServer struct {
}

func (UnimplementedConsumerServer) SubscribeOnScreenText(*ClientDataRequest, Consumer_SubscribeOnScreenTextServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeOnScreenText not implemented")
}
func (UnimplementedConsumerServer) Exec(Consumer_ExecServer) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedConsumerServer) mustEmbedUnimplementedConsumerServer() {}

// UnsafeConsumerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsumerServer will
// result in compilation errors.
type UnsafeConsumerServer interface {
	mustEmbedUnimplementedConsumerServer()
}

func RegisterConsumerServer(s grpc.ServiceRegistrar, srv ConsumerServer) {
	s.RegisterService(&Consumer_ServiceDesc, srv)
}

func _Consumer_SubscribeOnScreenText_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConsumerServer).SubscribeOnScreenText(m, &consumerSubscribeOnScreenTextServer{stream})
}

type Consumer_SubscribeOnScreenTextServer interface {
	Send(*ClientDataOnScreenTextResponse) error
	grpc.ServerStream
}

type consumerSubscribeOnScreenTextServer struct {
	grpc.ServerStream
}

func (x *consumerSubscribeOnScreenTextServer) Send(m *ClientDataOnScreenTextResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Consumer_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConsumerServer).Exec(&consumerExecServer{stream})
}

type Consumer_ExecServer interface {
	SendAndClose(*ClientExecData) error
	Recv() (*ClientExecOutput, error)
	grpc.ServerStream
}

type consumerExecServer struct {
	grpc.ServerStream
}

func (x *consumerExecServer) SendAndClose(m *ClientExecData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *consumerExecServer) Recv() (*ClientExecOutput, error) {
	m := new(ClientExecOutput)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Consumer_ServiceDesc is the grpc.ServiceDesc for Consumer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Consumer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "client_data_pb.Consumer",
	HandlerType: (*ConsumerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeOnScreenText",
			Handler:       _Consumer_SubscribeOnScreenText_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _Consumer_Exec_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ClientData.proto",
}
